### ISSUE TITLE
team-based version?

### ISSUE THREAD

**Issue by billw1** [x07x08/VScript-TFDB#1]
ozfortress is interested in running a tfdb cup. Their servers arent set up for tfdb and it'd be convenient to just drop a single map in there that works with vscript only. Is this possible with a little bit of work?

**Comment by x07x08** [comment]
It is already team-based (TF2 is). The To-Do section is more about balance and gameplay ideas.

**Comment by billw1** [comment]
oh my bad. all the videos I saw were just against a bot
